// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1iKXG-coPNh8mdY1t52Mp4BYwFHEI3AE',
    appId: '1:109219529382:web:be3d1275c1a52e55892a67',
    messagingSenderId: '109219529382',
    projectId: 'mproject-391c7',
    authDomain: 'mproject-391c7.firebaseapp.com',
    storageBucket: 'mproject-391c7.appspot.com',
    measurementId: 'G-8Z1XWZKH4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWtg7r71n3cdQik8vZ9Hv3L8oIfIj1648',
    appId: '1:109219529382:android:c9b4490966531b3c892a67',
    messagingSenderId: '109219529382',
    projectId: 'mproject-391c7',
    storageBucket: 'mproject-391c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdV1RgquGzDSBfH0x3JVwv43q3HKvkJuk',
    appId: '1:109219529382:ios:81fe9ea96e4807e7892a67',
    messagingSenderId: '109219529382',
    projectId: 'mproject-391c7',
    storageBucket: 'mproject-391c7.appspot.com',
    androidClientId: '109219529382-vkiqi8p5kci530ffoh2aepjfgi12bc61.apps.googleusercontent.com',
    iosClientId: '109219529382-ou7r445eh7o3e1ut5h2dd86j01ksel8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.mProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdV1RgquGzDSBfH0x3JVwv43q3HKvkJuk',
    appId: '1:109219529382:ios:81fe9ea96e4807e7892a67',
    messagingSenderId: '109219529382',
    projectId: 'mproject-391c7',
    storageBucket: 'mproject-391c7.appspot.com',
    androidClientId: '109219529382-vkiqi8p5kci530ffoh2aepjfgi12bc61.apps.googleusercontent.com',
    iosClientId: '109219529382-ou7r445eh7o3e1ut5h2dd86j01ksel8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.mProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1iKXG-coPNh8mdY1t52Mp4BYwFHEI3AE',
    appId: '1:109219529382:web:6d43d1704175d804892a67',
    messagingSenderId: '109219529382',
    projectId: 'mproject-391c7',
    authDomain: 'mproject-391c7.firebaseapp.com',
    storageBucket: 'mproject-391c7.appspot.com',
    measurementId: 'G-D4V6JB4HCE',
  );

}